name: plots # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple graph plotter for GNOME # 79 char long summary
description: |
  Plots makes it easy to visualise mathematical formulae. In addition to basic
  arithmetic operations, it supports trigonometric, hyperbolic, exponential and
  logarithmic functions, as well as arbitrary sums and products. Plots is
  designed to integrate well with the GNOME desktop and takes advantage of
  modern hardware using OpenGL.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  plots:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - PyOpenGL == 3.1.5
      - Jinja2 == 2.11.2
      - numpy == 1.18.4
      - lark-parser == 0.9.0
      - importlib_resources

apps:
  plots:
    command: bin/plots
    extensions: [gnome-3-34]
    slots:
      - dbus-daemon
    common-id: com.github.alexhuntley.Plots
